# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Block Health Check (dd32)

on: repository_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Block Testing Framework
      run: npm ci
    - name: Configure & Start Environment
      run: npm run wp-env start
    - name: Run End to End Tests
      id: testRunDirectory
      run: npm run test:e2e
    - name: Debug
      uses: mxschmitt/action-tmate@v2
